language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0

matrix:
  exclude:
    - env: TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=0
      php: 7.0
    - env: TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=0
      php: 7.1
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
      php: 7.0
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
      php: 7.1
  include:
    - php: 7.2
      env: TYPO3_VERSION=^7.6 COVERAGE=0 FUNCTIONAL=1
    - php: 5.6
      env: TYPO3_VERSION=^7.6 COVERAGE=0 FUNCTIONAL=1
    - php: 7.0
      env: TYPO3_VERSION=^8.7 COVERAGE=1 FUNCTIONAL=1
    - php: 7.2
      env: TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=1
    - php: 7.2
      env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
    - php: 7.3
sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  # Enables us to test dev-master
  - composer config minimum-stability dev
  - composer config prefer-stable true
  # Installs nimut/typo3-complete
  - travis_wait 300 composer require --dev nimut/typo3-complete=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json;
  - export TYPO3_PATH_ROOT=$PWD/.Build/Web;
  - export UNIT_XML=".Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml"
  - export FUNCTIONAL_XML=".Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml"

script:
  # Execute unit tests
  - >
    echo "Running unit tests";
    if [[ "$COVERAGE" == "1" ]]; then
      .Build/bin/phpunit --whitelist Classes/ --coverage-clover=unittest-coverage.clover --colors -c $UNIT_XML Tests/Unit

      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
    else
      .Build/bin/phpunit --colors -c $UNIT_XML Tests/Unit
    fi

  # Execute functional tests, if enabled
  - >
    if [[ "$FUNCTIONAL" == "1" ]]; then
      echo "Running functional tests"
      export typo3DatabaseHost="localhost";
      export typo3DatabaseName="typo3";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      .Build/bin/phpunit --colors -c $FUNCTIONAL_XML Tests/Functional/
    fi

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
